const INVENTARIO_AGENCIAS = {
    "Kavak Sur::INV-001": {
        "id_interno": "INV-001",
        "agencia": "Kavak Sur",
        "marca": "VOLKSWAGEN",
        "modelo": "JETTA",
        "año": 2021,
        "version": "Highline",
        "kilometraje": 45000,
        "precio_venta": 350000,
        "color": "Rojo",
        "transmision": "Automática",
        "motor": "1.4T 150hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Volkswagen Jetta 2021 en su versión Highline. Excelente estado, servicios de agencia y garantía extendida.",
        "link_fotos": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "Kavak Sur::INV-002": {
        "id_interno": "INV-002",
        "agencia": "Kavak Sur",
        "marca": "NISSAN",
        "modelo": "VERSA",
        "año": 2022,
        "version": "Advance",
        "kilometraje": 25000,
        "precio_venta": 280000,
        "color": "Gris",
        "transmision": "Manual",
        "motor": "1.6L 118hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Nissan Versa 2022 Advance, muy poco kilometraje. Ideal para ciudad, muy ahorrador y seguro.",
        "link_fotos": "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "Dalton Honda::INV-003": {
        "id_interno": "INV-003",
        "agencia": "Dalton Honda",
        "marca": "HONDA",
        "modelo": "CIVIC",
        "año": 2020,
        "version": "EX-L",
        "kilometraje": 55000,
        "precio_venta": 420000,
        "color": "Blanco",
        "transmision": "Automática",
        "motor": "2.0L 158hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Honda Civic 2020 EX-L. Un clásico de confiabilidad con acabados premium y tecnología avanzada.",
        "link_fotos": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "Autos Lindavista::INV-004": {
        "id_interno": "INV-004",
        "agencia": "Autos Lindavista",
        "marca": "CHEVROLET",
        "modelo": "TRACKER",
        "año": 2023,
        "version": "LTZ",
        "kilometraje": 15000,
        "precio_venta": 410000,
        "color": "Azul",
        "transmision": "Automática",
        "motor": "1.2T 130hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Chevrolet Tracker 2023 LTZ. Como nueva, gran espacio interior y el mejor consumo de combustible en su segmento.",
        "link_fotos": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "Kavak Sur::INV-005": {
        "id_interno": "INV-005",
        "agencia": "Kavak Sur",
        "marca": "MAZDA",
        "modelo": "3",
        "año": 2019,
        "version": "i Grand Touring",
        "kilometraje": 70000,
        "precio_venta": 320000,
        "color": "Rojo",
        "transmision": "Automática",
        "motor": "2.5L 186hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Mazda 3 2019 i Grand Touring. El diseño Kodo en su máxima expresión, manejo deportivo y acabados de lujo.",
        "link_fotos": "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "automundo_1": {
        "id_interno": "AUTO-001",
        "agencia": "Automundo",
        "marca": "MINI",
        "modelo": "COOPER",
        "año": 2024,
        "version": "S Hot Chili",
        "kilometraje": 21013,
        "precio_venta": 625000,
        "color": "Gris oscuro",
        "transmision": "Automática",
        "motor": "2.0T 192hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Mini Cooper S 2024 Hot Chili. Una experiencia de manejo tipo Go-Kart con el estilo único de Mini.",
        "link_fotos": "https://images.unsplash.com/photo-1551106602-a434ff396f1b?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "automundo_2": {
        "id_interno": "AUTO-002",
        "agencia": "Automundo",
        "marca": "ACURA",
        "modelo": "ILX",
        "año": 2021,
        "version": "A-Spec",
        "kilometraje": 34976,
        "precio_venta": 479000,
        "color": "Rojo",
        "transmision": "Automática",
        "motor": "2.4L 201hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Acura ILX 2021 A-Spec. Sedán deportivo de lujo con gran desempeño y equipo de sonido premium.",
        "link_fotos": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "automundo_4": {
        "id_interno": "AUTO-004",
        "agencia": "Automundo",
        "marca": "MAZDA",
        "modelo": "CX-5",
        "año": 2022,
        "version": "S Grand Touring",
        "kilometraje": 54226,
        "precio_venta": 449000,
        "color": "Blanco",
        "transmision": "Automática",
        "motor": "2.5L 188hp",
        "traccion": "Delantera",
        "combustible": "Gasolina",
        "descripcion": "Mazda CX-5 2022 S Grand Touring. SUV elegante, segura y con una de las mejores cabinas en su clase.",
        "link_fotos": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    },
    "automundo_5": {
        "id_interno": "AUTO-005",
        "agencia": "Automundo",
        "marca": "CHEVROLET",
        "modelo": "SILVERADO",
        "año": 2021,
        "version": "1500 V6 Cabina Doble",
        "kilometraje": 48723,
        "precio_venta": 469000,
        "color": "Blanco",
        "transmision": "Automática",
        "motor": "4.3L V6",
        "traccion": "4x2",
        "combustible": "Gasolina",
        "descripcion": "Chevrolet Silverado 2021. Potencia y capacidad de carga incomparables para el trabajo o viajes.",
        "link_fotos": "https://images.unsplash.com/photo-1591165736611-28bc9c0957b9?auto=format&fit=crop&w=1200",
        "estatus": "disponible"
    }
};
